[package]
name = "world"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.11.2"
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = ["macros"] }

[[bin]]
name = "world"
path = "src/world.rs"
