service: world-lambda

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  memorySize: 128

functions:
  getWorld:
    handler: main
    package:
      artifact: target/lambda/world/bootstrap.zip

package:
  individually: true

plugins:
  - serverless-cargo-plugin

custom:
  cargo:
    prebuilt: true
    workspace: ../
